apiVersion: v1
kind: Service 
metadata:
  name: frontend-svc 
  namespace: expense
  labels:
    description: this-is-main-frontend-service 
spec:
  selector: 
    tier: frontend
    component: web
  ports:
  - protocol: TCP
    port: 8079
    targetPort: 8079