apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend-target-group-binding
  namespace: expense
spec:
  serviceRef:
    name: frontend-svc # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:343430925817:targetgroup/expense-dev-frontend-TG/d5373b79c9e1ea6d