apiVersion: v1
kind: Service 
metadata:
  name: backend-svc 
  namespace: expense
  labels:
    description: This-is-backende-main-service
spec:
  selector: 
    version: v1.0.0
    description: This-is-backende-blue-deployment-v1.0.0
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080