apiVersion: v1
kind: Service 
metadata:
  name: backend-svc 
  labels:
    description: this-is-main-backend-service 
spec:
  selector: 
    version: v1.0.0
    description: This-is-blue-deployment-v1.0.0
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080